# Generated by Django 4.2.2 on 2023-06-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="nivel_perfil",
            field=models.CharField(
                choices=[
                    ("D", "Padrão"),
                    ("B", "Bonze"),
                    ("P", "Prata"),
                    ("O", "Ouro"),
                ],
                default="D",
                max_length=1,
            ),
        ),
    ]
